[package]
name = "single_sign"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
single_sign_types = { path = "../../single_sign_types" }
